# Generated by Django 4.2.5 on 2023-09-24 11:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('title', models.CharField(max_length=15, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('content', models.TextField()),
            ],
        ),
    ]
